CREATE TABLE PRODUCT(
    PNO NUMBER PRIMARY KEY,
    PNAME VARCHAR2(20),
    PRICE NUMBER,
    REG_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_PNO
NOCACHE;

COMMIT;

SELECT TO_CHAR(SYSDATE, 'FMYYYY"³â "MM"¿ù "DD"ÀÏ"') FROM DUAL;